{% set name = "elastic-apm" %}
{% set version = "6.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/elastic-apm-{{ version }}.tar.gz
  sha256: 0d4b5724731304b10a24c19e4bf666fb6acd1def3b6f23453090d305383fe9a5

build:
  number: 0
  noarch: python
  script_env: ELASTIC_APM_WRAP_EXTENSIONS=false
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
  run:
    - certifi
    - python >=3.6,<4.0
    - urllib3

test:
  imports:
    - elasticapm
    - elasticapm.conf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/elastic/apm-agent-python
  summary: The official Python module for Elastic APM
  dev_url: https://github.com/elastic/apm-agent-python
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beniwohli
    - tobiasraabe
