{% set name = "elastic-apm" %}
{% set version = "6.7.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/elastic-apm-{{ version }}.tar.gz
  sha256: b4d853d74381c356ca4c4a42f4a4b51a1933128793aebf1af32d74633a500205

build:
  number: 0
  noarch: python
  script_env: ELASTIC_APM_WRAP_EXTENSIONS=false
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
  run:
    - certifi
    - python >=3.6,<4.0
    - urllib3

test:
  imports:
    - elasticapm
    - elasticapm.conf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/elastic/apm-agent-python
  summary: The official Python module for Elastic APM
  dev_url: https://github.com/elastic/apm-agent-python
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beniwohli
    - tobiasraabe
